[[language]]
name = "typescript"
scope = "source.ts"
injection-regex = "^(ts|typescript)$"
file-types = ["ts"]
shebangs = ["node", "deno"]
roots = ["deno.json", "package.json", "tsconfig.json"]
language-servers = ["deno"]
formatter = { command = "prettier", args = ["--parser", "typescript"] }
indent = { tab-width = 2, unit = "  " }
auto-format = true

[language-server.deno]
command = "deno"
args = ["lsp"]

[language-server.deno.config]
enable = true
lint = true
unstable = true

